### ISSUE TITLE
http.client.UnknownProtocol: HTTP/2.0

### ISSUE THREAD

**Issue by CLWcynthia** [DXMarkets/Savoir#11]
I use python3.6 on Windows to connect to ubuntu's multichain, and in multichain.Conf has configured IP, but I keep reporting an error, and I can't solve it. What's the reason?
```
`Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "D:\anaconda\lib\http\client.py", line 319, in begin
    raise UnknownProtocol(version)
http.client.UnknownProtocol: HTTP/2.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 438, in send
    timeout=timeout
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "D:\anaconda\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "D:\anaconda\lib\http\client.py", line 319, in begin
    raise UnknownProtocol(version)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', UnknownProtocol('HTTP/2.0',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/pyfile/DPBC/activity_json.py", line 49, in <module>
    main()
  File "F:/pyfile/DPBC/activity_json.py", line 46, in main
    conn_multichain()
  File "F:/pyfile/DPBC/activity_json.py", line 37, in conn_multichain
    print(api.getinfo())
  File "D:\anaconda\lib\site-packages\Savoir\Savoir.py", line 58, in __call__
    r = requests.post(url, data=encoded, headers=self.__headers)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\lib\site-packages\requests\sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\lib\site-packages\requests\adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', UnknownProtocol('HTTP/2.0',))`
```

this is my python script
```
` from Savoir import Savoir
 rpcuser = 'multichainrpc'
    rpcpasswd = 'password'
    rpchost = 'ubuntu_ip'
    rpcport = '9578'
    chainname = 'chain_test'
    api = Savoir(rpcuser, rpcpasswd, rpchost, rpcport, chainname)
    print(api.getinfo())`
```

**Comment by CLWcynthia** [comment]
I use ubuntu16.04 and python2.7 ，it’s work

**Comment by reiven** [comment]
Hi, thanks, actually the lib was only tested with Python 2.7. We should make it Python3 compatible. Please feel free to close this issue and open other for this.
