### ISSUE TITLE
Savoir TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by Fulcrum11** [DXMarkets/Savoir#5]
Hi,
I would like to experiment with multichain in Python, but I just cannot figure it out. It always raises the TypeError: 'module' object is not callable error, I checked on stackoverflow, where the solution is the "from Savoir import Savoir" statement, but it doesn't have any effect. I use Python in the Anaconda environment, version 3.5. I saw that you recently updated the code to Python 3 version. When I try to run the example:

```
from Savoir import Savoir

rpcuser = 'multichainrpc'
rpcpasswd = password from the config file
rpchost = ip address
rpcport = '2765'
chainname = 'chain1'
api = Savoir(rpcuser, rpcpasswd, rpchost, rpcport, chainname)
print(api)
api.getinfo()
```
 
Traceback (most recent call last):

  File "<ipython-input-5-bdf4bf8e8c33>", line 1, in <module>
    runfile('O:/blockchain/savoirtest.py', wdir='O:/blockchain')

  File "C:\Users\pk\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\pk\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "O:/blockchain/savoirtest.py", line 24, in <module>
    api = Savoir(rpcuser, rpcpasswd, rpchost, rpcport, chainname)

TypeError: 'module' object is not callable

Thanks in advance!

**Comment by reiven** [comment]
Hi @Fulcrum11 try to remove the following line

```python
print(api)
```
and just use the `api.getinfo()` call

How did you install the package? cloning the repo from github or with pip?
FYI i've personally never tested in windows environment

**Comment by Fulcrum11** [comment]
Hi @reiven , I have installed it via pip.
The problem is at the `Savoir(rpcuser, rpcpasswd, rpchost, rpcport, chainname)` line, removing the print() doesn't change the result.
Now I tried in Python2.7, and it works (the code runs, and if I call `print(api.getinfo())` I  get the relevant data), so it must be an issue of Python3.

**Comment by oxydaemon** [comment]
Just adding a note, this is same issue as issue #4 

Workaround as suggested there works for me:
Change import line to:
from Savoir.Savoir import Savoir

**Comment by reiven** [comment]
Thanks for the suggestions @oxydaemon and @Fulcrum11 
I've update the import file and updated the pip package

Can you please check it?

**Comment by anju728** [comment]
has anyone resolved this issue?
